config/routes.rb
Rails.application.routes.draw do
  resources :reports do
    resources :comments, controller: "reports/comments"
  end
  resources :books do
    resources :comments, controller: "books/comments"
  end

  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :user_relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:github]

  has_one_attached :avatar

  has_many :active_relationships, class_name: 'UserRelationship', foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'UserRelationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth['provider'], uid: auth['uid']) do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['nickname']
      user.email = User.dummy_email(auth)
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # ダミーのアドレスを用意
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = User.from_omniauth(request.env['omniauth.auth'].except('extra'))
      sign_in_and_redirect @user
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    def update
      super
      resource.avatar.attach(account_update_params[:avatar]) if account_update_params[:avatar].present?
    end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/views/users/followers.html.erb
<h1><%= t('.followers_page') %></h1>

<% @users.each do |user| %>
  <hr>
  <% if user.followed_by?(current_user) %>
    <p><strong><%= link_to user.name, user_path(user.id) %></strong></p>
    <p><%=link_to t('.followed'), user_user_relationships_path(user.id), method: :delete %></p>
  <% else %>
    <p><strong><%= link_to user.name, user_path(user.id) %></strong></p>
    <p><%=link_to t('.following'), user_user_relationships_path(user.id), method: :post %></p>
  <% end %>  
<% end %>

app/views/users/follows.html.erb
<h1><%= t('.follows_page') %></h1>

<% @users.each do |user| %>
  <hr>
  <p><strong><%= link_to user.name, user_path(user.id) %></strong></p>
  <p><%=link_to t('.followed'), user_user_relationships_path(user.id), method: :delete %></p>
<% end %>

app/views/users/index.html.erb
<h1><%= t('.users_page') %></h1>
<% @users.each do |user| %>
  <% if user.name != current_user.name %>
    <hr>
    <% if current_user != user %>
      <% if user.followed_by?(current_user) %>
        <p><strong><%= link_to user.name, user_path(user.id) %></strong></p>
        <p><%= link_to t('.followed'), user_user_relationships_path(user.id), method: :delete %></p>
      <% else %>
        <p><strong><%= link_to user.name, user_path(user.id) %></strong></p>
        <p><%= link_to t('.following'), user_user_relationships_path(user.id), method: :post %></p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= User.human_attribute_name(:name) %></h1>
<%= @user.name %>
<h3><%= User.human_attribute_name(:email) %></h3>
<%= @user.email %>
<h3><%= User.human_attribute_name(:avatar) %></h3>
<%= image_tag @user.avatar.variant(resize:'500x500').processed if @user.avatar.attached? %>
<h3><%= User.human_attribute_name(:postal_code) %></h3>
<%= @user.postal_code %>
<h3><%= User.human_attribute_name(:street_address) %></h3>
<%= @user.street_address %>
<h3><%= User.human_attribute_name(:profile) %></h3>
<%= @user.profile %>
<% if @user == current_user %>
  <h3><%= t('.follows') %></h3>
  <%= link_to t('.follows_page'), follows_user_path(current_user.id) %>
  <h3><%= t('.follower') %></h3>
  <%= link_to t('.followers_page'), followers_user_path(current_user.id) %>
<% else %>
  <% if @user.followed_by?(current_user) %>
        <p><strong><%= @user.name %></strong></p>
        <p><%= link_to t('.followed'), user_user_relationships_path(@user.id, current_user.id), method: :delete %></p>
      <% else %>
        <p><strong><%= @user.name %></strong></p>
        <p><%= link_to t('.following'), user_user_relationships_path(@user.id), method: :post %></p>
      <% end %>   
<% end %>

<h3><%= @user.name %><%= t('.books')%></h3>
<table>
  <thead>
    <tr>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:memo) %></th>
      <th><%= Book.human_attribute_name(:author) %></th>
      <th><%= Book.human_attribute_name(:picture) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.memo %></td>
        <td><%= book.user.name %></td>
        <td><%= image_tag(book.picture_url, class: 'books_img') if book.picture.present? %></td>
        <% if current_user == book.user %>
        <td><%= link_to t('.show'), book %></td>
        <td><%= link_to t('.edit'), edit_book_path(book) %></td>
        <td><%= link_to t('.destroy'), book, method: :delete, data: { confirm: t('.confirm') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>