config/routes.rb
Rails.application.routes.draw do
  resources :reports do
    resources :comments, controller: "reports/comments"
  end
  resources :books do
    resources :comments, controller: "books/comments"
  end

  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :user_relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  include Commentable
end

app/controllers/books/comments_controller.rb
class Books::CommentsController < ApplicationController
  before_action :set_book
  before_action :set_book_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @book.comments.all.page params[:page]
  end

  def show; end

  def new
    @comment = @book.comments.new
  end

  def edit
    @comment
  end

  def create
    @comment = @book.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to book_comments_path, notice: t('notice_create_comment')
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to book_comments_path, notice: t('notice_update_comment')
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to book_comments_path, notice: t('notice_destroy_comment')
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_book_comment
    @comment = @book.comments.find_by!(id: params[:id], user_id: current_user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :validates_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all.page params[:page]
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to @book, notice: t('notice_create')
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: t('notice_update')
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: t('notice_destroy')
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end

    def validates_user
      redirect_to root_path, alert: t('validates_user_alert') if @book.user_id != current_user.id
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>

  <%= render 'layouts/error_messages', model: book %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', book: @book %>

<%= link_to t('.show'), @book %> |
<%= link_to t('.back'), books_path %>

app/views/books/index.html.erb
<h1><%= t('.books') %></h1>

<table>
  <thead>
    <tr>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:memo) %></th>
      <th><%= Book.human_attribute_name(:author) %></th>
      <th><%= Book.human_attribute_name(:picture) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.memo %></td>
          <td><%= book.user.name %></td>
          <td><%= image_tag(book.picture_url, class: 'books_img') if book.picture.present? %></td>
          <td><%= link_to t('.show'), book %></td>
          <% if current_user == book.user %>
          <td><%= link_to t('.edit'), edit_book_path(book) %></td>
          <td><%= link_to t('.destroy'), book, method: :delete, data: { confirm: t('.confirm') } %></td>
          <% end %>
        </tr>
      <% end %> 
  </tbody>
</table>

<br>

<%= link_to t('.new_book'), new_book_path %>

<%= paginate @books %>

app/views/books/new.html.erb
<h1><%= t('.new_book') %></h1>

<%= render 'form', book: @book %>

<%= link_to t('.back'), books_path %>

app/views/books/show.html.erb
<p>
  <strong><%= Book.human_attribute_name(:title) %>:</strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:memo) %>:</strong>
  <%= @book.memo %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:author) %>:</strong>
  <%= @book.user.name %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:picture) %>:</strong>
  <%= image_tag(@book.picture_url) if @book.picture.present? %>
</p>
<% if current_user == @book.user %>
<%= link_to t('.edit'), edit_book_path(@book) %> |
<% end %>
<%= link_to t('.back'), books_path %>
<%= link_to t('.comments'), book_comments_path(@book) %> |
<%= link_to t('.new_comment'), new_book_comment_path(@book) %>