config/routes.rb
Rails.application.routes.draw do
  resources :reports do
    resources :comments, controller: "reports/comments"
  end
  resources :books do
    resources :comments, controller: "books/comments"
  end

  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :user_relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
end

app/models/report.rb
class Report < ApplicationRecord
  include Commentable
  belongs_to :user
  validates :title, :body, :user_id, presence: true
end

app/controllers/reports/comments_controller.rb
class Reports::CommentsController < ApplicationController
  before_action :set_report
  before_action :set_report_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @report.comments.all.page params[:page]
  end

  def show; end

  def new
    @comment = @report.comments.new
  end

  def edit
    @comment
  end

  def create
    @comment = @report.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to report_comments_path, notice: t('notice_create_comment')
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to report_comments_path, notice: t('notice_update_comment')
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to report_comments_path, notice: t('notice_destroy_comment')
  end

  private

  def set_report
    @report = Report.find(params[:report_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_report_comment
    @comment = @report.comments.find_by!(id: params[:id], user_id: current_user.id)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :validates_user, only: [:edit, :update, :destroy]

  def index
    @reports = Report.all.page params[:page]
  end

  def show; end

  def new
    @report = Report.new
  end

  def edit; end

  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id

    if @report.save
      redirect_to @report, notice: t('notice_create_report')
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      redirect_to @report, notice: t('notice_update_report')
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_url, notice: t('notice_destroy_report')
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:title, :body)
  end

  def validates_user
    redirect_to report_comments_path(@report), alert: t('validates_user_alert') if @report.user_id != current_user.id
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>

  <%= render 'layouts/error_messages', model: report %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', report: @report %>

<%= link_to t('.show'), @report %> |
<%= link_to t('.back'), reports_path %>

app/views/reports/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= Report.human_attribute_name(:title) %></th>
      <th><%= Report.human_attribute_name(:body) %></th>
      <th><%= Report.human_attribute_name(:user) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.body %></td>
        <td><%= report.user.name %></td>
        <td><%= link_to t('.show'), report %></td>
        <% if current_user == report.user %>
        <td><%= link_to t('.edit'), edit_report_path(report) %></td>
        <td><%= link_to t('.destroy'), report, method: :delete, data: { confirm: t('.confirm') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new_report'), new_report_path %>

<%= paginate @reports %>

app/views/reports/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', report: @report %>

<%= link_to t('.back'), reports_path %>

app/views/reports/show.html.erb
<p>
  <strong><%= Report.human_attribute_name(:title) %>:</strong>
  <%= @report.title %>
</p>

<p>
  <strong><%= Report.human_attribute_name(:body) %>:</strong>
  <%= @report.body %>
</p>

<% if current_user == @report.user %>
<%= link_to t('.edit'), edit_report_path(@report) %> |
<% end %>
<%= link_to t('.back'), reports_path %> |
<%= link_to t('.comments'), report_comments_path(@report) %> |
<%= link_to t('.new_comment'), new_report_comment_path(@report) %>