config/routes.rb
Rails.application.routes.draw do
  resources :reports do
    resources :comments, controller: "reports/comments"
  end
  resources :books do
    resources :comments, controller: "books/comments"
  end

  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :user_relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, t('.error')) %> <%= t('.message') %></h2>

      <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
          <% if user_signed_in? %>
            <strong><%= link_to current_user.name, user_path(current_user.id) %></strong>
            <%= link_to t('.edit_profile'), edit_user_registration_path %>
            <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
            <%= link_to t('.books'), books_path %>
            <%= link_to t('.users'), users_path %>
            <%= link_to t('.reports'), reports_path %>
          <% else %>
            <%= link_to t('.sign_up'), new_user_registration_path %>
            <%= link_to t('.login'), new_user_session_path %>
          <% end %>
      </nav>
    </header>
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>